### PR TITLE
Recolor icon.svg to fit project rebranding

### PR DESCRIPTION
**Pull request by Majoramari**
A recoloring of the default icon to match the new colors of our beloved Redot engine!

The rebranding has some coloring and UX issues. I’m planning to open an issue to track them, but let's start with this.

This PR could possibly start helpin' with #688 and #657

### CODE REVIEW

**Comment by RadenTheFolf** [comment]
Was this saved as a plain svg or an inkscape svg? It should be a plain svg. it should also be passed through svgcleaner as described here https://docs.godotengine.org/en/stable/contributing/development/editor/creating_icons.html

**Comment by SkogiB** [comment]
> Was this saved as a plain svg or an inkscape svg? It should be a plain svg. it should also be passed through svgcleaner as described here https://docs.godotengine.org/en/stable/contributing/development/editor/creating_icons.html

We really need to fix the .svg workflow man lmao

**Comment by Majoramari** [comment]
> Was this saved as a plain svg or an inkscape svg? It should be a plain svg. it should also be passed through svgcleaner as described here https://docs.godotengine.org/en/stable/contributing/development/editor/creating_icons.html

Thanks for guiding me in the right direction, and sorry for any confusion.

This time, I followed the guide and saved it as a plain SVG instead of an Inkscape SVG!

I also cleaned it using `svgcleaner` as shown below:

It's now 1.4 KB in size.

```
svgcleaner --multipass svg_source.svg svg_optimized.svg
```

> NOTE: The project is archived, so I guess we should start using an alternative.

Please let me know if there's anything that needs to be changed.

**Comment by tokengamedev** [comment]
Please take a note at the issue I have raised https://github.com/Redot-Engine/redot-engine/issues/69.

**Pull request closed without merging**
