### PR TITLE
Add a Frames option to the Timer node.

### PR DESCRIPTION
**Pull request by CoreTaxxe**
Adds the option to have timers run with frames instead of time. Works with idle and physics options to choose either physics or normal process. They are used for frame-perfect timings such as in doom-like games or fighting games.

### CODE REVIEW

**Review by dreamnook — APPROVED** [review]

**Review by Aleksandar-Argead — APPROVED** [review]

**Comment by Eisendroid** [comment]
Nice. Useful feature

**Review by x64x2 — APPROVED** [review]

**Review by shoyguer — APPROVED** [review]
LGTM!

**Review by Murly117 — APPROVED** [review]

**Review by dandykong — APPROVED** [review]

**Review by filipworksdev — APPROVED** [review]

**Comment by Veradictus** [comment]
I like it

**Comment by filipworksdev** [comment]
This is good!

**Review by JohnnyThunder2 — APPROVED** [review]
Code looks good from my eye.

**Comment by Spartan322** [comment]
This needs to be rebased, also does this have a related Godot proposal and/or PR? I would also like to try pushing this upstream before merging, but if you don't wish Godot to have it then we'll investigate merging it in a way to minimize merge conflicts.

**Comment by CoreTaxxe** [comment]
> This needs to be squashed, also does this have a related Godot proposal and/or PR? I would also like to try pushing this upstream before merging, but if you don't wish Godot to have it then we'll investigate merging it in a way to minimize merge conflicts.

It does. But they were deadset on not adding it so I cba to discuss that there any longer. The only merge conflict that could arise afaik is fro a not-yet-merged pr about bhvr QOL changes. Nothing big, however. We can keep this open until that PR gets merged upstream and I rebase/solve conflicts. Howover I fear that might take some time (waiting for the upstream merge not fixing it :p)

**Comment by SkogiB** [comment]
> > This needs to be squashed, also does this have a related Godot proposal and/or PR? I would also like to try pushing this upstream before merging, but if you don't wish Godot to have it then we'll investigate merging it in a way to minimize merge conflicts.
> 
> It does. But they were deadset on not adding it so I cba to discuss that there any longer. The only merge conflict that could arise afaik is fro a not-yet-merged pr about bhvr QOL changes. Nothing big, however. We can keep this open until that PR gets merged upstream and I rebase/solve conflicts. Howover I fear that might take some time (waiting for the upstream merge not fixing it :p)

Squash the commits and if Godot takes much longer to change their minds, we'll pull the trigger on this one without waiting Godot too long. We don't have a fixed amount of time we wait for upstream to do things, but yeah. Can't have our people waiting 3 months for Godot when the point of things was to bypass that. Get this squashed and we'll be g2g whenever we decide to do it.

**Comment by CoreTaxxe** [comment]
This got a bit messy with the double fork repo hope rebase went well

**Comment by SkogiB** [comment]
> ~This got a bit messy with the double fork repo hope rebase went well~
> 
> Okay I cant figure out why github wont update the PR.

Messy git stuff is fun! I'll see if one of the core guys has time to help you with it, I'm not much of a git wizard

**Comment by SkogiB** [comment]
Spartan says you need to force push it to your remote and it should go in (glorious force push!!!)
The push you're trying to do includes the squash correct?

**Comment by CoreTaxxe** [comment]
> Spartan says you need to force push it to your remote and it should go in (glorious force push!!!) The push you're trying to do includes the squash correct?

Yessn't I tried to figure out why git was infinitely stuck on processing after I did the **force** push after rebase. Did not squash yet. I'm gonna try a reset tomorrow 🤷

**Comment by CoreTaxxe** [comment]
grafik
Branch looks like this. No idea what else I could try. Probably gonna nuke the branch + pr and reopen on new if github doesn't update until tomorrow.

**Comment by Spartan322** [comment]
You need to fetch the upstream then rebase on stop of the upstream's master, if you have Redot-Engine as your upstream then you can do:
```sh
git fetch upstream
git rebase upstream/master
git rebase -i upstream/master
# squash with the interactive rebase
git push -f origin redot-frame-timer
```

**Comment by CoreTaxxe** [comment]
> You need to fetch the upstream then rebase on top of the upstream's master, if you have Redot-Engine as your upstream then you can do:
> 
> ```shell
> git fetch upstream
> git rebase upstream/master
> git rebase -i upstream/master
> # squash with the interactive rebase
> git push -f origin redot-frame-timer
> ```
> 
> if you need to set Redot-Engine as your upstream then you need to do this beforehand:
> 
> ```shell
> git remote add upstream https://github.com/Redot-Engine/redot-engine
> ```

This is exactly what I did

**Comment by Spartan322** [comment]
Its kinda difficult to help from here then, if your on the discord I could help better, ping Spartan322 in the redot-discussion channel then.

**Comment by CoreTaxxe** [comment]
Closing due to github having lost or cut reference to branch after redot became stand-alone. Branch can no longer be updated. Openend new PR.

**Pull request closed without merging**
