### PR TITLE
Remove tests

### PR DESCRIPTION
**Pull request by passwordbuddy**
This PR removes all tests from the Redot Engine.

## Changes
- Removed all tests

## Why Tests Are Woke
1. Tests promote over-inclusivity: They encourage an environment where every edge case must be accounted for. This mindset is pushing an agenda of "over-inclusiveness" where even the most obscure bugs are invited into our pristine codebase. We believe only the strongest code should survive.

2. Tests coddle weak developers: Writing tests is a form of hand-holding that fosters dependency. By removing tests, we allow developers to embrace their true potential, free from the "woke" safety net that forces them to question everything they write.

3. Real code doesn’t need validation: If you’re a good coder, you don’t need tests to prove it. Tests are a symptom of imposter syndrome, where developers feel the need to constantly prove their work is valid. True confidence comes from shipping code, not from caving to the demands of "woke" QA practices.

## Conclusion
This PR is a step toward reclaiming the Redot Engine for true developers who don’t need tests to back up their skills. Let’s focus on real code, not inclusive practices that dilute the development process.

### CODE REVIEW

**Comment by muhuk** [comment]
Childish spam.

**Comment by DaloLorn** [comment]
To be entirely fair to him, I've seen nothing yet to convince me this fork was meant for anything else.

**Comment by Withaust** [comment]
PRs like this only prove reasons for forks like this to exist

**Comment by duck4i** [comment]
Brilliant. 😂

**Comment by Salvakiya** [comment]
Spam/not useful

**Pull request closed without merging**
