### PR TITLE
Changing the default color theme to a red base tone.

### PR DESCRIPTION
**Pull request by Vcoder89**
Changes the base tone to red, to match reddot theme. It's a grayish red with accessibility in mind.

### CODE REVIEW

**Comment by Vcoder89** [comment]
image

**Comment by Andrew-Fright** [comment]
In my humble opinion its awesome idea

**Review by Andrew-Fright — CHANGES_REQUESTED** [review]
why not just remove original values that being overwritten
preset_contrast = 0.0;
preset_draw_extra_borders = true;
} else { // Default
    preset_accent_color = Color(0.23, 0.11, 0.16);
    preset_base_color = Color(0.14, 0.12, 0.12);
    preset_contrast = config.default_contrast;
}

**Review by wesamdev — CHANGES_REQUESTED** [review]
please make colors more bright because the text hard  to see

**Comment by Vcoder89** [comment]
> why not just remove original values that being overwritten preset_contrast = 0.0; preset_draw_extra_borders = true; } else { // Default preset_accent_color = Color(0.23, 0.11, 0.16); preset_base_color = Color(0.14, 0.12, 0.12); preset_contrast = config.default_contrast; }

Sorry what do you mean with this?

**Comment by Vcoder89** [comment]
> please make colors more bright because the text hard to see

True, the problem is that red is not accessibility friendly, so more bright might not be a good idea. I'll try a few other styles later Today.

**Comment by Vcoder89** [comment]
> why not just remove original values that being overwritten preset_contrast = 0.0; preset_draw_extra_borders = true; } else { // Default preset_accent_color = Color(0.23, 0.11, 0.16); preset_base_color = Color(0.14, 0.12, 0.12); preset_contrast = config.default_contrast; }

Good point, I missed that, I'll sort that out.

**Comment by TokisanGames** [comment]
Sorry, but this is unattractive and a big step backwards in aesthetic. Red is not a good color for broad use in graphic design. It's best for accents. I can't think of any major software or website that uses it except overstock, which is atrocious. Even then it's still only an accent.

With such a fundamental change, this is not something one person should be attempting to insert without opening a proposal so a wide audience and leadership can decide on it.

IMO, the default theme should be Passive Star's which is very attractive, already widely popular, professionally designed, and unlikely to be adopted upstream.

https://github.com/passivestar/godot-minimal-theme

**Comment by Vcoder89** [comment]
> Sorry, but this is unattractive and a big step backwards in aesthetic. Red is not a good color for broad use in graphic design. It's best for accents. I can't think of any major software or website that uses it except overstock, which is atrocious. Even then it's still only an accent.
> 
> With such a fundamental change, this is not something one person should be attempting to insert without opening a proposal so a wide audience and leadership can decide on it.
> 
> IMO, the default theme should be Passive Star's which is very attractive, already widely popular, professionally designed, and unlikely to be adopted upstream.
> 
> https://github.com/passivestar/godot-minimal-theme

You do understand the color scheme can be changed an infinite number of times right? I was purely trying to distance ourselves from Godot and Redot at the early start. It wasn't meant as a change that will remain like this for the next 10 years, it was suppose to be something temporary until the community settles on a unique theme.
You also seem to be oblivious to your hypocrisy, telling me it's a change of far higher importance than a mere plebe like me, while proceeding to tell me how it should be done with the Passive Star's approach.

Whatever dude, get off your high horse.

**Comment by TokisanGames** [comment]
I don't understand why you're so upset. I was in no way rude to you. There's no reason for you to be so. You misinterpreted the intent and content of the message. 

Your PR changes the default for potentially thousands of users. There already is infrastructure and precedent that such decisions are made via wide consensus. The appropriate step is to open a proposal to discuss options before implementation. I did not dictate or demand what the theme should be. I offered my opinion, made explicitly clear with "IMO". You can still open a proposal with a variety of options including red, passive star, and others. 

There will be many more opportunities for contributing, but you're not going to have a good time if you get so defensive when people share opinions. This entire website exists for people to comment, agree, disagree, and work together.

**Pull request closed without merging**
