### PR TITLE
Optimize the Web-Editor build and styles

### PR DESCRIPTION
**Pull request by MarekZeman91**
## BEFORE
Old Intro
Old Editor

## AFTER
New Intro
New Editor

### Main changes
- colors and naming changes to reflect the rebranding
- JavaScript in editor.html optimized
- CSS from editor.html moved to styles.css
- tabs are aligned to the right and have active state
- fixed JavaScript errors for missing variables
- removed JavaScript infinite focus loop

### IMPORTANT BUILD INFO
The web build works with UP TO `emsdk 3.1.67`.

Here is my Makefile:
```Makefile
build:
	../emsdk/emsdk install 3.1.67 && ../emsdk/emsdk activate 3.1.67 && source ../emsdk/emsdk_env.sh && scons platform=web target=editor

serve:
	python3 platform/web/serve.py
```

### CODE REVIEW

**Comment by SkogiB** [comment]
Awesome. I dunno the demand for it, but it looks like a good idea. Could you add a comparison image of before and after so people can quickly preview your changes? We'll take a look at this soon

Also, install pre-commit. We're trying to get everyone up to speed on that, it should help you pass the static checker easier.

**Comment by MarekZeman91** [comment]
> Awesome. I dunno the demand for it, but it looks like a good idea. Could you add a comparison image of before and after so people can quickly preview your changes? We can also cherry pick this to 4.3 later
> 
> Also, install pre-commit. We're trying to get everyone up to speed on that, it should help you pass the static checker easier.

I didn't not manage to get the pre-commit working. I use Lint and other tools daily but it didn't work well on this project. I fixed it from the info I got from CLI. Hope it is fine now.

**Comment by SkogiB** [comment]
> > Awesome. I dunno the demand for it, but it looks like a good idea. Could you add a comparison image of before and after so people can quickly preview your changes? We can also cherry pick this to 4.3 later
> > Also, install pre-commit. We're trying to get everyone up to speed on that, it should help you pass the static checker easier.
> 
> I didn't manage to get the pre-commit working. I use Lint and other tools daily but it didn't work well on this project. I fixed it from the info I got from CLI. Hope it is fine now.

Sorry for the delays man, running the workflow now to check the fixes, once we know stuff is good we just need the commits squashed so it doesn't clutter the commit history and we're good to go on this!

**Comment by Spartan322** [comment]
Could this be squashed?

**Review by Norrox — APPROVED** [review]

**Pull request closed without merging**
