### PR TITLE
Update logo_outlined.svg

### PR DESCRIPTION
**Pull request by Starkium**
test force size

### CODE REVIEW

**Comment by Starkium** [comment]
static checks seem fine, other checks that might fail are related to parent branch

**Comment by cinderbrick1212** [comment]
> static checks seem fine, other checks that might fail are related to parent branch

font and spacing does not work well

**Comment by Starkium** [comment]
> > static checks seem fine, other checks that might fail are related to parent branch
> 
> font and spacing does not work well

correct, this isn't the final image. This was a test to ensure the sizing of the image worked correctly

**Review by tindrew — APPROVED** [review]

**Comment by RadenTheFolf** [comment]
Since an official branding packages has been released and is posted in an announcement on the Redot Discord server does this pr need to remain open as it currently is?

**Comment by RadenTheFolf** [comment]
Official branding is now available as a zip file located under announcements in the Redot Discord

Thank you for your efforts!

**Pull request closed without merging**
