### PR TITLE
To be deleted. (Admin)

### PR DESCRIPTION
**Pull request by x8c8r**
nah

### CODE REVIEW

**Comment by Withaust** [comment]
PRs like this only prove reasons for forks like this to exist

**Comment by x8c8r** [comment]
> PRs like this only prove reasons for forks like these to exist

well maybe if you guys werent losers who think that queer people breathing is politics then people wouldnt make PRs like this and you wouldnt make forks like these

**Comment by Zerocchi** [comment]
Thanks for proving the Redot community is doing the right thing.

**Comment by CoreTaxxe** [comment]
> > PRs like this only prove reasons for forks like these to exist
> 
> well maybe if you guys werent losers who think that queer people breathing is politics then people wouldnt make PRs like this and you wouldnt make forks like these

Man you really showed them how mature you are!

**Comment by x8c8r** [comment]
> > > PRs like this only prove reasons for forks like these to exist
> > 
> > 
> > well maybe if you guys werent losers who think that queer people breathing is politics then people wouldnt make PRs like this and you wouldnt make forks like these
> 
> Man you really showed them how mature you are!

yea and so did you guys by throwing a hissy fit and forking the engine for no real reason

**Comment by bombitmanbomb** [comment]
> > > > PRs like this only prove reasons for forks like these to exist
> > > 
> > > 
> > > well maybe if you guys werent losers who think that queer people breathing is politics then people wouldnt make PRs like this and you wouldnt make forks like these
> > 
> > 
> > Man you really showed them how mature you are!
> 
> yea and so did you guys by throwing a hissy fit and forking the engine for no real reason

Anyone can fork any open source project for Any reason. Welcome to open source

**Comment by mrjustaguy** [comment]
What's wrong with this PR? Aren't Prebuilt Game Engines Woke?
The Tweet that set this chain of events in motion surely seems to think so.
image

On a more serious note, I don't see this fork surviving long, as there aren't serious developers working on it, like there are on Godot.
This whole situation is just absolute BS from BOTH Sides, acting like little Children, with Mods on one side going on an overzealous ban spree banning those that broke Godot's Codes of Conduct https://godotengine.org/code-of-conduct/ and ended up banning some that didn't, and The other side Failing to Take a Joke.
While IMO Wokot is a bad joke and Godot should've just replied with the intended message behind it (that using prebuild engines doesn't mean the users are x,y or z, and that they don't prevent anybody from using their engine period)

**Review by JohnnyThunder2 — CHANGES_REQUESTED** [review]
The woke stuff has already been removed....

**Comment by muhuk** [comment]
> What's wrong with this PR? Aren't Prebuilt Game Engines Woke? The Tweet that set this chain of events in motion surely seems to think so. image
> 
> On a more serious note, I don't see this fork surviving long, as there aren't serious developers working on it, like there are on Godot. This whole situation is just absolute BS from BOTH Sides, acting like little Children, with Mods on one side going on an overzealous ban spree banning those that broke Godot's Codes of Conduct https://godotengine.org/code-of-conduct/ and ended up banning some that didn't, and The other side Failing to Take a Joke. While IMO Wokot is a bad joke and Godot should've just replied with the intended message behind it (that using prebuild engines doesn't mean the users are x,y or z, and that they don't prevent anybody from using their engine period)

A weak attempt at gaslighting.

**Comment by Entity325** [comment]
Whoever these "woke" people are, they must really see Redot as a threat if they keep trying to sabotage it like this.

Disruptive activity like this is against Github TOS.

**Comment by mrjustaguy** [comment]
I'm not woke, and I'm not trying to disrupt this fork, I'm just stating the facts that I see, and what I see is a fork with no development expertise on board. Granted it's only the early days of the fork, but it's more likely that an existing Fork of Godot will gain traction over a brand new one with nobody behind it

**Comment by x8c8r** [comment]
> Whoever these "woke" people are, they must really see Redot as a threat if they keep trying to sabotage it like this.
> 
> Disruptive activity like this is against Github TOS.

i really dont see it as a threat i doubt you all will even manage to implement 1 feature successfully. why i am doing this is because i think your goal is stupid

**Comment by muhuk** [comment]
> why dont you just not engage and work on the engine instead

Blocked on GH.

**Comment by Entity325** [comment]
> > Whoever these "woke" people are, they must really see Redot as a threat if they keep trying to sabotage it like this.
> > Disruptive activity like this is against Github TOS.
> 
> i really dont see it as a threat i doubt you all will even manage to implement 1 feature successfully. why i am doing this is because i think your goal is stupid
> 
> also why dont you just not engage and work on the engine instead, wouldnt that be more productive than arguing with a random person

If it's not a threat, why are you submitting hostile and disruptive pull requests? The people working on this fork only want to exist. They aren't even concerned about existing in your space, that's why they created a fork. You never had to interact with or even acknowledge them.

Repositories do not need a reason to justify their existence. You're the who invaded their space, and you're the one attacking them. What's got you so hostile about someone just wanting to exist without harming anything?

**Comment by mrjustaguy** [comment]
Indeed they don't need to justify their existence.

Personally, my Problem with this fork is more the fact that the Media coverage around this New fork is gaslighting people into thinking this fork will be a "fixed" Godot, fixing the "slow progress in development" which this project is extremely unlikely to do for aforementioned reasons, as well as the fact that this whole situation is plain stupid internet extremism in action, because nuance doesn't seem to exist on the internet.

**Comment by Saul2022** [comment]
> Personally, my Problem with this fork is more the fact that the Media coverage around this New fork is gaslighting people into thinking this fork will be a "fixed" Godot, fixing the "slow progress in development" 

You're not wrong though, but ultimately wel'l see how it goes, it's kinda soon to see , and it obvious it wont merge pr as fast as godot( remi is a pretty good merger), but we yet know nothing , the only thing though is they said this decision was not spontaneous , but that was planned  some time ago , and prob published it now , for marketing reassons.

**Comment by temotskipa** [comment]
Just close and nuke this PR already. WTF is this

**Comment by mrjustaguy** [comment]
Idk how spontaneous this was, as to me it really looks reactionary, with no thought put into the actual execution of it beyond hoping everyone jumps ship, which is unlikely given these factors:
1) Devs that do good work in Godot are likely already on the payroll
2) Aren't aware of what's going on
3) Don't see this as not going anywhere due to Godot's existing momentum

The only event really that I see could actually cause a genuine mass exodus is Godot attempting to change their Licensing, because believe it or not, most just don't care about this type of drama that's currently going on

**Comment by Entity325** [comment]
> Idk how spontaneous this was, as to me it really looks reactionary, with no thought put into the actual execution of it beyond hoping everyone jumps ship, which is unlikely given these factors:
> 
> 1. Devs that do good work in Godot are likely already on the payroll
> 2. Aren't aware of what's going on
> 3. Don't see this as not going anywhere due to Godot's existing momentum
> 
> The only event really that I see could actually cause a genuine mass exodus is Godot attempting to change their Licensing, because believe it or not, most just don't care about this type of drama that's currently going on

If we take your statements at face value, then the Redot fork is harmless and interacting with it is a waste of time and effort. You are making claims that the fork will receive no beneficial contributions, take nothing away from the main branch, and die within a few months. If this is true, then the best course of action for you to take would simply be to ignore it.

Yet here you are, desperately trying to convince the maintainers of how futile their efforts are, backing up your claims with demonstrable falsehoods.

The maintainers of this fork just wanted to exist, and that triggers you.

**Comment by FredericLueck** [comment]
> > PRs like this only prove reasons for forks like these to exist
> 
> well maybe if you guys werent losers who think that queer people breathing is politics then people wouldnt make PRs like this and you wouldnt make forks like these

I am bisexual and I spit on people like you

**Comment by mrjustaguy** [comment]
Fascinating.

Has it perhaps occurred to you that I'm in here for much more, mundane reasons?
Like idk, maybe having some fun, or wanting to help and voicing my criticisms, that sorry, aren't demonstrable falsehoods otherwise you'd have made your arguments demonstrating how they are falsehoods instead of just labeling them such.

I mean my first post here should've really signaled motives rather clearly I'd have thought.
I'm both having some fun with the Absurd Situation, and I'm voicing criticisms towards the overall Situation.
If those aren't motives worth the little effort it takes to write, I honestly don't know why People do anything besides eating and sleeping.

**Comment by gnuchanos** [comment]
it's funny

**Comment by Salvakiya** [comment]
spam and not serious

**Pull request closed without merging**
