### PR TITLE
[4.3] Fix `ColorPicker` overbright indicator position

### PR DESCRIPTION
**Pull request by Spartan322**
(cherry picked from commit blazium-engine/blazium@f7c6762df94867d93465612ec6be86b28593dc47)

### CODE REVIEW

**Review by SkogiB — APPROVED** [review]

**Comment by Captain-Wet-Beard** [comment]
Verified on Github
image

**Comment by Spartan322** [comment]
@Captain-Wet-Beard How about you read https://github.com/godotengine/godot/blob/master/AUTHORS.md and https://github.com/Redot-Engine/redot-engine/blob/master/REDOT_AUTHORS.md first, its pretty explicitly clear that neither represent copyright, and the license is still MIT, only the git blame is covered under copyright and he is credited.

**Comment by Captain-Wet-Beard** [comment]
>the license is still MIT

Since your PR admits youre cherrypicking Blazium PRs, are you planning to add a line to your copy of the MIT license for Blazium contributors?

**Comment by Spartan322** [comment]
No, first our LICENSE.txt will not change, secondly it there was no copyright for blazium when the commit was made, even in future cherry-picks its not actually required if the commit makes proper reference to the repo at the time it was cherry-picked which it does regardless.

**Comment by LokiFawkes** [comment]
Whales is in the AUTHORS.md file, so clearly author credit is not the issue. Seems like Blazium just wants attention.

**Comment by Captain-Wet-Beard** [comment]
> Whales is in the AUTHORS.md file, so clearly author credit is not the issue.

I must have missed where AUTHORS.md is mentioned in the wording of the MIT license.

I was just pointing out a potential copyright problem out of friendly concern, it really doesn't effect me one way or the other if you choose to play fast and loose with licenses.

Feel free to interpret my good faith concern in any way you wish, like I said it isnt my problem.

**Pull request merged**
