### PR TITLE
[4.3] Replace 'Godot' with 'Redot' in Documentation

### PR DESCRIPTION
**Pull request by Majoramari**
Same as #708 but for version 4.3

### CODE REVIEW

**Review by decryptedchaos — APPROVED** [review]
Looks good

**Comment by Spartan322** [comment]
This needs to be squashed, also the PR title and first line of the commit message need to be shortened, you can put more detail in the PR description the rest of the commit message, just the title and first line of the commit message need to be shorter.

**Comment by Majoramari** [comment]
> This needs to be squashed, also the PR title and first line of the commit message need to be shortened, you can put more detail in the PR description the rest of the commit message, just the title and first line of the commit message need to be shorter.

As far as I understand I'm done with what you asked for!

**Review by Spartan322 — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
