### PR TITLE
Dark Gray and Red Default Theme for Redot that match vibes :) 

### PR DESCRIPTION
**Pull request by QuantumBlazeGames**

### CODE REVIEW

**Comment by Comdfsfsfas** [comment]
If you want to change the default theme of Redot, I think you should not just change the main color of the editor interface, but also adjust the values ​​​​of some buttons, borders, etc.
[The interface can be improved like this](https://www.bilibili.com/video/BV1Vt2FYmE2k/?spm_id_from=333.337.search-card.all.click&vd_source=386903b379d9d4345a69b6102e5dd88e)
[The youtube link of the video.](https://www.youtube.com/watch?v=WmZq3UgOGKY)
[The GitHub link in the video.](https://github.com/passivestar/godot-minimal-theme)

I'm sorry that I am currently unable to manipulate the Redot source code personally.

**Comment by wesamdev** [comment]
image

**Comment by Comdfsfsfas** [comment]
> image

It looks better than before.

**Comment by wesamdev** [comment]
i have add minmal theme and inter font and #251

**Pull request closed without merging**
