### PR TITLE
Remove woke

### PR DESCRIPTION
**Pull request by lvxnull**

### CODE REVIEW

**Comment by Spartan322** [comment]
This is a spam PR, this should be closed, ignore it and report the user.

**Comment by lvxnull** [comment]
no youre just too woke to understand

**Comment by lvxnull** [comment]
merge if true anti woke patriot
ignore or report if woke communist

**Comment by jlitewski** [comment]
The bait used to be believable...

**Comment by lvxnull** [comment]
idk sounds like something a woke communist would say

**Comment by lvxnull** [comment]
1984

**Comment by jakiki6** [comment]
I smell woke communist vuvuzela no iphone 101128309421 quadrazillion ded

**Pull request closed without merging**
