### PR TITLE
Add One Pixel Snap Button to the Tile Data Editor

### PR DESCRIPTION
**Pull request by valkyrienyanko**
There is no "One Pixel Snap" button so this PR adds one.

P.S. I'm not sure if the button should be called "One-Pixel Snap" or "Pixel Snap".

Untitled

### CODE REVIEW

**Comment by Spartan322** [comment]
This new option needs a different icon.

**Comment by SkogiB** [comment]
Such a good feature man, fantastic. Second Spartan's request for a unique icon for pixel snapping

**Comment by shoyguer** [comment]
@Spartan322 @valkyrienyanko 
I created this .svg files, hope it helps.
SnapPixel

**Comment by valkyrienyanko** [comment]
Thank you @shoyguer 

image

**Comment by Spartan322** [comment]
Would you be alright having this submitted upstream to Godot or do you want this to be a Redot only thing?

**Comment by valkyrienyanko** [comment]
@Spartan322 You can submit this to Godot upstream if you want.

**Comment by Spartan322** [comment]
Alright I'll cherry-pick it to upstream, see what they say about it.

**Comment by Spartan322** [comment]
Actually I probably shouldn't throw this upstream without a proposal but I can't just submit a proposal to Godot without a good case for its use, so I'm not really able to submit this upstream, if someone who needs this would like to submit a proposal, that be great.

**Comment by SkogiB** [comment]
SVG static checker reeeeeeeeeeee

**Comment by SkogiB** [comment]
If you get pre-commit installed this should hopefully pass the static check for the .svg

**Comment by Majoramari** [comment]
> If you get pre-commit installed this should hopefully pass the static check for the .svg

@valkyrienyanko Hey use this command to help you with the svg checker
```sh
svgo --config=misc/utility/svgo.config.mjs <input.svg> -o output.svg
```
Make sure to install svgo

**Comment by Spartan322** [comment]
It be better to just install [pre-commit](https://pre-commit.com/) and just run it as it already handles that.

**Comment by valkyrienyanko** [comment]
Alright I've ran pre-commit and it modified the svg. I've pushed new commit with these changes.

**Comment by Majoramari** [comment]
> Alright I've ran pre-commit and it modified the svg. I've pushed new commit with these changes.

Thanks if you could squash the commits to the first 1 only

**Comment by valkyrienyanko** [comment]
Squashed

**Review by SkogiB — APPROVED** [review]

**Review by Spartan322 — APPROVED** [review]

**Pull request merged**
