### PR TITLE
Fix the visual studio project creation

### PR DESCRIPTION
**Pull request by tokengamedev**
Fixed the debugging issue after Visual studio project creation
Also updated all the properties for visual studio project from Godot to Redot

### CODE REVIEW

**Comment by SkogiB** [comment]
Will review soon, we're in the middle of getting a release done but after that is prime time for fixes and things like that. Appreciate the input man, we'll check back soon

**Comment by SkogiB** [comment]
Needs to be retargeted at master, and also done for 4.3, standby for Trashguy and Spartan to touch base

**Comment by tokengamedev** [comment]
If you want me rebase the fix to master. I will do that, let me know. It was based on branding fixes. 
It should not conflict with any other fixes.

**Comment by Spartan322** [comment]
The redot-rebranding branch is dead, this needs to target 4.3 and master.

**Comment by tokengamedev** [comment]
closing this pull request and will create a new one as the amount of fix has to be done for rebasing is too much.

**Pull request closed without merging**
