### PR TITLE
Replace 'Godot' with 'Redot' in Documentation

### LINKED ISSUE #706: [4.3] `application/boot_splash/image` documentation still refers to Godot
### Tested versions

410ced2

### System information

N/A

### Issue description

Boot splash image documentation has not been correctly updated to refer to Redot.

### Steps to reproduce

1. Open/Create project.
2. Open Project Settings.
3. Filter for `application/boot_splash/image`.
4. Hover over Image.
5. See: 
image

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Majoramari**
Fixes #706 
This PR solve some issues with Redot docs like #706 
image

And more

### CODE REVIEW

**Review by Spartan322 — APPROVED** [review]
Looks good, could you also throw a once-over for the 4.3 branch too if you would.

**Review by SkogiB — APPROVED** [review]
Looks good to me, looking forward the 4.3 one as well, Thanks man

**Comment by Majoramari** [comment]
Please wait I'll change references in this PR and #713

**Review by decryptedchaos — COMMENTED** [review]
Missed ref to [RDShaderFile]

- doc/translations/zh_CN.po
- doc/classes/ResourceImporterShaderFile.xml

**Review by decryptedchaos — APPROVED** [review]
Ok good to go,  we'll fix the RDShaderFile ref in another PR after we fix the class name.

**Comment by Spartan322** [comment]
Could this please be squashed first.

**Comment by Majoramari** [comment]
> Could this please be squashed first.

Squashed

**Comment by Spartan322** [comment]
Thank you.

**Pull request merged**
