### PR TITLE
[4.3] Overhaul `CanvasItemEditor` snap lines drawing and input

### PR DESCRIPTION
**Pull request by Spartan322**
(cherry picked from commit blazium-engine/blazium@5ca9caa0f88c7ee4c9cad38decf0a064eb126bab)

### CODE REVIEW

**Comment by DeanLemans** [comment]
Do you guys have any original pr?
Your only cherry picking from blazium the last couple days

**Comment by Spartan322** [comment]
#709
#726
#746
#747
#750

**Comment by Spartan322** [comment]
Also
#148
#734
#764

**Comment by SkogiB** [comment]
> Do you guys have any original pr(s) planned? Your only cherry picking from blazium the last couple days.

We also steal PRs from Godot I'll have you know!

**Review by SkogiB — APPROVED** [review]

**Pull request merged**
