### PR TITLE
Redot rebranding (Deref Godot: doc/) + fixed email / repo points

### PR DESCRIPTION
**Pull request by mcdubhghlas**
Removal of a lot of Godot references. There are still some, but they exist for a reason (email +copyright, would break code, etc.)

I had to fix an email, plus changed several references to a fraudulent repo.

### CODE REVIEW

**Review by Spartan322 — COMMENTED** [review]
Should be squaushed and the PR and commit should say something like `Fix docs referencing Godot to Redot` or something.

**Comment by decryptedchaos** [comment]
- doc/translations/de.po

still needs Deref in the repo URL still has the repo name as godot

**Comment by mcdubhghlas** [comment]
Good catch!

**Review by decryptedchaos — COMMENTED** [review]
Everything looks good,  Except want to get some clarification from the rest of the team on these 

I thought we decided to revert this to Godot Shader Language on the same premise that we are keeping GDScript  as it reduces confusion on compatibility.  

- doc/classes/VisualShaderNodeIntFunc.xml
- doc/classes/VisualShaderNodeIntOp.xml
- doc/classes/VisualShaderNodeUIntFunc.xml
- doc/classes/VisualShaderNodeUIntOp.xml

**Comment by SkogiB** [comment]
> Everything looks good, Except want to get some clarification from the rest of the team on these
> 
> I thought we decided to revert this to Godot Shader Language on the same premise that we are keeping GDScript as it reduces confusion on compatibility.
> 
> * doc/classes/VisualShaderNodeIntFunc.xml
> * doc/classes/VisualShaderNodeIntOp.xml
> * doc/classes/VisualShaderNodeUIntFunc.xml
> * doc/classes/VisualShaderNodeUIntOp.xml

Correct, we need to revert any instances of "RDShader", "Redot Shader Language" etc

**Comment by mcdubhghlas** [comment]
I'll get this sorted later and try to squash everything together. If worst comes to worst, I'll just redo this unless someone wants to let me know what I need to run.

**Pull request closed without merging**
