### PR TITLE
[4.3] Rebrand android editor to allow play store signing

### PR DESCRIPTION
**Pull request by trashguy**
Rebrand of the android object naming to allow upload to the Google play store and signing. This will allow users to load the app on their Android devices.

We are waiting on Google to approve our account, so lets keep this open until I can verify the builds on the Play store.

### CODE REVIEW

**Review by Spartan322 — APPROVED** [review]

**Review by kayofontinhas — APPROVED** [review]

**Review by Spartan322 — CHANGES_REQUESTED** [review]
Can confirm these changes currently crash on my android emulator.

**Comment by Spartan322** [comment]
`platform/android/java_godot_lib_jni.h` and `platform/android/plugin/godot_plugin_jni.h` need their function names changed to reflect the package.

**Comment by trashguy** [comment]
Patched your changes @Spartan322  and updated the editor name

**Comment by Spartan322** [comment]
This needs to be squashed, you can add my name to the commit for Github by adding `Co-authored-by: Spartan322 <Megacake1234@gmail.com>` at the end of the commit.

**Review by Spartan322 — APPROVED** [review]

**Pull request merged**
