### PR TITLE
Update Logo Font and Enhance Visibility (Brandkit 1.1)

### LINKED ISSUE #690: Redot Logo needs to be desaturated for darker backgrounds
### Tested versions

4.4

### System information

Windows 11

### Issue description

In case of darker backgrounds like in task bar or other places it looks odd and hurts the eye, but in white background it looks ok 
e.g., in windows startup compared to other red logos
image

the way to handle this without impacting hue is by reducing the saturation of colors.
currently the saturation is at 100%, it can be reduced by ~20%

The example given below is for comparison of various saturation values
icons

If any other technique known, it can be applied too.

### Steps to reproduce

icons in editor

### Minimal reproduction project (MRP)

N.A

### LINKED ISSUE #757: Why inconsistent font usage in logos?
### Tested versions

master

### System information

repo

### Issue description

https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png

which one is correct which one is wrong?

### Steps to reproduce

compare these
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/master/logo_outlined.png

https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.svg
https://github.com/Redot-Engine/redot-engine/blob/redot-rebranding/logo_outlined.png

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Majoramari**
Fixes Redot-Engine/redot-proposals#23
Fixes #757
[Read more on discord](https://discord.com/channels/1290063237223551046/1295486950710710282/1295486950710710282)

This PR changes the logo font of the logo from Futura to Heebo based on the updated Brand Kit 1.1.

The dark background issue is addressed by using the outlined version of the logo as an icon. 
image

The `TitleBarLogo.svg` has been updated with a lighter font and outlines for better visibility.
image

An easier to see splash screen.
image

Additionally, low-quality images in the root directory have been replaced with better-quality alternatives, and the missing outline versions have also been added.

Thanks for your time!

### CODE REVIEW

**Comment by tokengamedev** [comment]
There is still a fix coming from joey, it has not been addressed yet for https://github.com/Redot-Engine/redot-proposals/issues/23 (previously issue 690). Suggest waiting for the update from Joey.

**Comment by Majoramari** [comment]
> There is still a fix coming from joey, it has not been addressed yet for [Redot-Engine/redot-proposals#23](https://github.com/Redot-Engine/redot-proposals/issues/23) (previously issue 690). Suggest waiting for the update from Joey.
> 
> Unless this has to go for 4.3 release

This proposal is fixed here

**Comment by a-irsyad** [comment]
For consistency, "Redot Game Engine" or "Redot Engine"?

**Comment by Majoramari** [comment]
> For consistency, "Redot Game Engine" or "Redot Engine"?

I can make it Engine again, I just from some reason followed what Godot do!

**Comment by a-irsyad** [comment]
> > For consistency, "Redot Game Engine" or "Redot Engine"?
> 
> I can make it Engine again, I just from some reason followed what Godot do!

I suggest go with "Redot Engine" for the splash screen as that what Andrew said, also in the guideline and website domain.

**Comment by Majoramari** [comment]
> I suggest go with "Redot Engine" for the splash screen as that what Andrew said, also in the guideline and website domain.

Should I stick to the thin font or use the ultra bold?

**Comment by a-irsyad** [comment]
> > I suggest go with "Redot Engine" for the splash screen as that what Andrew said, also in the guideline and website domain.
> 
> Should I stick to the thin font or use the ultra bold?

Heebo Ultra-Bold

**Comment by Majoramari** [comment]
> Heebo Ultra-Bold

Updated

image

**Review by Spartan322 — APPROVED** [review]
LGTM

**Review by SkogiB — APPROVED** [review]

**Pull request merged**
