### PR TITLE
Reference Hunting: tests/ thirdparty/

### PR DESCRIPTION
**Pull request by mcdubhghlas**
This covers:

```
tests/
thirdparty/
```

#270 - This should be fine. I am uncertain about changing variable names from "godot" to redot" so I left those.

### CODE REVIEW

**Review by verypleasentusername — APPROVED** [review]
honest work

**Comment by mcdubhghlas** [comment]
I'm keeping references to Godot 4.3 or lower in the comments because it pertains to compatibility with older versions.

**Comment by Bioblaze** [comment]
no way the workflow accepts this, but what the hell lets see.

**Comment by mcdubhghlas** [comment]
That last push was just the headers ONLY, the other references aren't modified in the 420 I changed.

**Pull request closed without merging**
